### ISSUE TITLE
Graphic glitch during AmbientMode

### ISSUE THREAD

**Issue by moWerk** [AsteroidOS/meta-sparrow-hybris#15]
Using nightly from 2021-12-24.
Trying to display colors during AmbientMode results in a 5 color representation on the screen.
The glitch is not to be seen on a screenshot, only on the screen in AmbientMode
![sparrow-fault6](https://user-images.githubusercontent.com/15074193/147423614-125ec5ca-4ed1-49ec-8eba-24f990abdb50.jpg)
.
Unaltered view during !displayAmbient:
![sparrow-fault5](https://user-images.githubusercontent.com/15074193/147423627-33ca50ce-309c-487a-a19d-68cec8ac60c9.jpg)

**Comment by danialbehzadi** [comment]
I think this should be addressed in watchface. Ambient mode is working as expected.

**Comment by moWerk** [comment]
> I think this should be addressed in watchface. Ambient mode is working as expected.

As a watchface designer, i am curious about wether this behaviour is isolated to sparrow (maybe wren and anthias) and should be mitigated by e.g. black and white conversions provided by the watchface/designer during ambientMode only for those watches.
Or if it would be advised to strictly limit ambientMode color use to black and white and those exact few colors matching the fixed pallette that seems to be available even on watches hit by this limitation.

I was not aware that this color limitation during ambientMode is expected behaviour on some watches and would like to discuss a strategy how to prevent other designers from running into the same question. E.g. by adding advise to the [Watchface creation guidelines](https://asteroidos.org/wiki/watchfaces-creation/#guidlines)

**Comment by FlorentRevest** [comment]
> I think this should be addressed in watchface. Ambient mode is working as expected.

I agree with @danialbehzadi here. I believe this is a technical limitation of ambient modes in general and even if colors could *maybe* work on some watches, I expect that all ambient watchfaces should stay black and white.

> As a watchface designer, i am curious about wether this behaviour is isolated to sparrow (maybe wren and anthias) and should be mitigated by e.g. black and white conversions provided by the watchface/designer during ambientMode only for those watches.
> Or if it would be advised to strictly limit ambientMode color use to black and white and those exact few colors matching the fixed pallette that seems to be available even on watches hit by this limitation.
> 
> I was not aware that this color limitation during ambientMode is expected behaviour on some watches and would like to discuss a strategy how to prevent other designers from running into the same question. E.g. by adding advise to the Watchface creation guidelines

I think the right solution is documentation yes.
Alternatively, we could maybe apply a desaturate effect https://doc.qt.io/qt-5/qml-qtgraphicaleffects-desaturate.html and a maximum contrast filter https://doc.qt.io/qt-5/qml-qtgraphicaleffects-brightnesscontrast.html#contrast-prop to force a black and white mode but I think it's best to leave the canvas free to watchface designers and trust them to do the right thing (with documentation)

I'm closing this bug because it's in the sparrow component, feel free to open a bug in asteroidos.org or just document it straight away ;)

**Comment by moWerk** [comment]
I am just going to document in https://asteroidos.org/wiki/watchfaces-creation/#guidlines
Since that solves the problem i see. Developers not aware of the problem running into it.
